# Generated by Django 5.1.5 on 2025-01-19 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='women',
            name='os_published',
        ),
        migrations.AddField(
            model_name='women',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
