# Generated by Django 5.1.5 on 2025-01-24 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0002_remove_women_os_published_women_is_published'),
    ]

    operations = [
        migrations.RenameField(
            model_name='women',
            old_name='contend',
            new_name='content',
        ),
    ]
