# Generated by Django 5.1.5 on 2025-01-24 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0003_rename_contend_women_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='women',
            old_name='cat',
            new_name='cat_id',
        ),
    ]
