# Generated by Django 5.1.5 on 2025-01-24 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0004_rename_cat_women_cat_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='women',
            old_name='cat_id',
            new_name='cat',
        ),
    ]
